-- The sequence of triangle numbers is generated by adding the natural numbers.
-- So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
-- ten terms would be:
--
-- 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
--
-- Let us list the factors of the first seven triangle numbers:
--
--  1: 1
--  3: 1,3
--  6: 1,2,3,6
-- 10: 1,2,5,10
-- 15: 1,3,5,15
-- 21: 1,3,7,21
-- 28: 1,2,4,7,14,28
--
-- We can see that 28 is the first triangle number to have over five divisors.
-- What is the value of the first triangle number to have over five hundred divisors?

factorize :: Integral a => a -> [a]
factorize x = findFactors 1 x []
  where findFactors a b lst =
          if a >= b then lst else
            if x `mod` a == 0 then
              let another = x `div` a in
                if another == a then findFactors (a+1) another ([a] ++ lst)
                else findFactors (a+1) another ([a, another] ++ lst)
            else findFactors (a+1) b lst


numFactors :: Integral a => a -> Int
numFactors x = length $ factorize x

fistTriangle limit = head . filter (\x -> numFactors x > limit) $ scanl (+) 1 [2..]
